server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springproject?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  application:
    name: project-oauth
mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml

#jwt config
jwt:
  keyPairName: jwt.jks
  keyPairAlias: jwt
  keyPairSecret: yanxinyu
  keyPairStoreSecret: yanxinyu
