spring:
  rabbitmq:
    host: 180.76.245.64
    port: 5672
    username: user
    password: password
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          # 最大尝试次数
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true
